server {
    listen 80;
    server_name _;

    # -----------------------------
    # STATIC WEBSITE (ROOT)
    # -----------------------------
    root /var/www/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # -----------------------------
    # NODE.JS API (/api)
    # -----------------------------
    location /api/ {
        proxy_pass http://127.0.0.1:3000/;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # -----------------------------
    # FLASK APP (/python)
    # -----------------------------
    location /python/ {
        proxy_pass http://127.0.0.1:5000/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # -----------------------------
    # LARAVEL APP (/laravel)
    # -----------------------------
    location /laravel/ {
        alias /var/www/devops-multi-app-deployment/laravel-app/public/;

        index index.php index.html;

        try_files $uri $uri/ /index.php?$query_string;

        # PHP-FPM HANDLER
        location ~ \.php$ {
            include snippets/fastcgi-php.conf;
            fastcgi_pass unix:/run/php/php8.3-fpm.sock;
            fastcgi_param SCRIPT_FILENAME $request_filename;
            include fastcgi_params;
        }
    }

    # -----------------------------
    # SECURITY (BLOCK HIDDEN FILES)
    # -----------------------------
    location ~ /\. {
        deny all;
    }
}
